<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * This code is borrowed from "views_block_filter_block" module.
 */
function elasticsearch_helper_views_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $storage = $form_state->getStorage();
  $view = $storage['view'];

  // Only react on block Views specifically configured with exposed form blocks.
  if (get_class($view->display_handler) == 'Drupal\elasticsearch_helper_views\Plugin\views\display\ElasticsearchBlock') {
    if ($view->display_handler->getOption('exposed_block')) {
      // Ensure that the fallback form action is the current page.
      $request = \Drupal::request();
      $url = Url::createFromRequest($request);
      $url->setAbsolute();
      $form['#action'] = $url->toString();
    }
  }
}
